Use soul for "\code"-box to allow multiline text
CybAtax/LaTeX-Template pull request #9
Opened 2023-02-16 15:53 UTC by JakobGrz

I didn't manage to use the preset color. Maybe one of you can do it.

2023-02-16 22:54 UTC, CybAtax requested changes

2023-02-16 22:54 UTC, CybAtax commented on settings/asset/codestyle.tex
> +\newcommand{\code}[1]{\ctext[RGB]{240,240,240}{#1}}
Kann man da auch xcolors angeben? Wäre mir lieber, dass man die gleichen Werte über verschiedener Befehle nutzen kann

2023-02-17 20:39 UTC, JakobGrz commented
Vor dem PR: 
![image](https://user-images.githubusercontent.com/109989829/219787345-3b4ac87b-86ce-47f8-ab20-68c71e7c7bfe.png)

Mit der Änderung:
![image](https://user-images.githubusercontent.com/109989829/219788282-2f63a181-50cd-4cf8-bfd6-8ffaf7e9ad9e.png)

Man könnte auch noch das Verhalten bei langen Wörtern verbessern. Bin mir da unsicher, was da ideal wäre.

2023-02-19 13:53 UTC, CybAtax commented
> Vor dem PR: ![image](https://user-images.githubusercontent.com/109989829/219787345-3b4ac87b-86ce-47f8-ab20-68c71e7c7bfe.png)
> 
> Mit der Änderung: ![image](https://user-images.githubusercontent.com/109989829/219788282-2f63a181-50cd-4cf8-bfd6-8ffaf7e9ad9e.png)
> 
> Man könnte auch noch das Verhalten bei langen Wörtern verbessern. Bin mir da unsicher, was da ideal wäre.

Für lange Wörter können im Zweifelsfall hyphenations angegeben werden, da kommt später was zu. Habe die beiden Commands noch zu einem gemacht und n Bugfix mit eingeschmuggelt, ich approve das jetzt, wenn das für dich passt kannst du das mergen @JakobGrz

2023-02-19 13:54 UTC, CybAtax approved these changes

2023-02-19 14:31 UTC, alex1701c approved these changes

2023-02-19 15:39 UTC, merged